spring:
  h2.console.enabled: true
  datasource:
    url: 'jdbc:h2:file:D:/devlearn/springwebapp/todoapp/todo-db'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password:
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: '*'
